spring:
  application:
    name: payments-ms

#Database configuration
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/foodcompany-payment?createDatabaseIfNotExist=true
    username: root
    password: root
  jpa:
    show-sql: true

#RabbitMQ Configuration
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    routing-key: "" #Empty RoutingKey due to FanoutExchange
    queue-name: completed-payments
    fanout-exchange-name: completed.payments.exchange


#Eureka Server Configuration
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${random.int}

server:
  port: 0