spring:
  application:
    name: payments-ms

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql:3306/foodcompany-payment?createDatabaseIfNotExist=true
    username: root
    password: root
  jpa:
    show-sql: true

  rabbitmq:
    host: rabbit1
    port: 5672
    username: guest
    password: guest
    queue-name: completed-payments
    fanout-exchange-name: completed.payments.exchange

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${random.int}

server:
  port: 0