CREATE TABLE payments (
    ID BIGINT(20) NOT NULL AUTO_INCREMENT,
    VALUE DECIMAL(19,2) NOT NULL,
    NAME VARCHAR(100) DEFAULT NULL,
    NUMBER VARCHAR(19) DEFAULT NULL,
    EXPIRATION VARCHAR(7) NOT NULL,
    CODE VARCHAR(3) DEFAULT NULL,
    STATUS VARCHAR(255) NOT NULL,
    PAYMENT_TYPE_ID BIGINT(20) NOT NULL,
    ORDER_ID BIGINT(20) NOT NULL,

    PRIMARY KEY (ID)
);